[versions]
agp = "8.5.2"
gradle = "8.7"
gradle-plugin = "5.1.0"
kotlin-gradle-plugin = "1.9.24"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
materialthemebuilder = { id = "dev.rikka.tools.materialthemebuilder", version = "1.4.1" }

# Dependencies section
[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-plugin = { module = "com.github.megatronking.stringfog:gradle-plugin", version.ref = "gradle-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
rikkax-appcompat = { module = "dev.rikka.rikkax.appcompat:appcompat", version = "1.6.1" }
rikkax-core = { module = "dev.rikka.rikkax.core:core", version = "1.4.1" }
rikkax-insets = { module = "dev.rikka.rikkax.insets:insets", version = "1.3.0" }
rikkax-layoutinflater = { module = "dev.rikka.rikkax.layoutinflater:layoutinflater", version = "1.3.0" }
rikkax-material = { module = "dev.rikka.rikkax.material:material", version = "2.7.0" }
rikkax-preference = { module = "dev.rikka.rikkax.material:material-preference", version = "2.0.0" }
rikkax-recyclerview = { module = "dev.rikka.rikkax.recyclerview:recyclerview-ktx", version = "1.3.2" }
rikkax-widget-borderview = { module = "dev.rikka.rikkax.widget:borderview", version = "1.1.0" }
rikkax-widget-mainswitchbar = { module = "dev.rikka.rikkax.widget:mainswitchbar", version = "1.1.0" }

androidx-activity = { module = "androidx.activity:activity", version = "1.8.1" }
androidx-browser = { module = "androidx.browser:browser", version = "1.7.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-core = { module = "androidx.core:core", version = "1.12.0" }
androidx-fragment = { module = "androidx.fragment:fragment", version = "1.7.0-alpha06" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.2.0-alpha01" }

material = { module = "com.google.android.material:material", version = "1.12.0" }

[bundles]
androidx = ["androidx-activity", "androidx-browser", "androidx-constraintlayout", "androidx-core", "androidx-fragment", "androidx-preference", "androidx-recyclerview", "androidx-swiperefreshlayout"]
rikkax = ["rikkax-appcompat", "rikkax-core", "rikkax-insets", "rikkax-layoutinflater", "rikkax-material", "rikkax-preference", "rikkax-recyclerview", "rikkax-widget-borderview", "rikkax-widget-mainswitchbar", "material"]
